# ---- Server ----
server.port=${SERVER_PORT:8080}
spring.application.name=ChatAppBackend
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
# ---- CORS ----
cors.allowed-origins=${CORS_ALLOWED_ORIGINS}
# ---- Redis ----
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD:}
# ---- Web Socket (split into individual env vars) ----
ws.signaling.path=${WS_SIGNALING_PATH}
ws.allowed-origin-patterns=${WS_ALLOWED_ORIGIN_PATTERNS}
ticket.ttl-seconds=${TICKET_TTL_SECONDS}
# ---- Firebase Admin (split into individual env vars) ----
# firebase.config.json=${FIREBASE_CONFIG_JSON}
firebase.type=${FIREBASE_TYPE}
firebase.private-key=${FIREBASE_PRIVATE_KEY}
firebase.project-id=${FIREBASE_PROJECT_ID}
firebase.private-key-id=${FIREBASE_PRIVATE_KEY_ID}
firebase.client-email=${FIREBASE_CLIENT_EMAIL}
firebase.client-id=${FIREBASE_CLIENT_ID}
firebase.auth-uri=${FIREBASE_AUTH_URI}
firebase.token-uri=${FIREBASE_TOKEN_URI}
firebase.auth-provider-x509-cert-url=${FIREBASE_AUTH_PROVIDER_X509_CERT_URL}
firebase.client-x509-cert-url=${FIREBASE_CLIENT_X509_CERT_URL}
# ---- Resend API Key ----
resend.api-key=${RESEND_API_KEY}
resend.from=${RESEND_FROM}
